[colors]

# Default colors
[colors.primary]
background = "#282a3a" 
foreground = "#eaf2f1" 

# Normal colors
[colors.normal]
black   = "#161821"  
red     = "#ff657a" 
green   = "#bad761" 
yellow  = "#ffd76d"  
blue    = "#ff9b5e"  
magenta = "#c39ac9"  
cyan    = "#9cd1bb"  
white   = "#eaf2f1"  

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
decorations = "buttonless"
dynamic_padding = true
startup_mode = "windowed"

opacity = 1.0
blur = true

option_as_alt = "both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 13.5
