import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2
decorations = "full"

opacity = 1.0
blur = true

option_as_alt = "both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14
