# Nordic.nvim inspired Alacritty theme

[colors]
  [colors.primary]
    background = '#242933'  # Base color - Dark background
    foreground = '#D8DEE9'  # Base color - Light foreground

  [colors.cursor]
    text = '#2E3440'        # Cursor text color
    cursor = '#D8DEE9'      # Cursor color

  [colors.normal]
    black   = '#3B4252'
    red     = '#BF616A'
    green   = '#A3BE8C'
    yellow  = '#EBCB8B'
    blue    = '#81A1C1'
    magenta = '#B48EAD'
    cyan    = '#88C0D0'
    white   = '#E5E9F0'

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2
decorations = "none"
dynamic_padding = true
startup_mode = "windowed"

opacity = 1.0
blur = true

option_as_alt = "both"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 13.5
